name: Trigger Central Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  trigger-central:
    name: Trigger Central Repository Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Central Pipeline
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"event_type":"trigger_full_pipeline"}' \
          https://api.github.com/repos/Skyphoenixx/TerraformAWSFlask/dispatches
